# Generated by Django 4.2.2 on 2023-06-08 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('isbn_number', models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(10, 'ISBN must be 10 or 13 digits long.'), django.core.validators.MaxLengthValidator(13, 'ISBN must be 10 or 13 digits long.')])),
                ('number_of_pages', models.IntegerField()),
                ('cover_link', models.URLField()),
                ('publication_language', models.CharField(max_length=50)),
            ],
        ),
    ]
