# Generated by Django 4.2.2 on 2023-06-08 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'ISBN must be 10 or 13 digits long.'), django.core.validators.MaxLengthValidator(13, 'ISBN must be 10 or 13 digits long.')]),
        ),
    ]
