# Generated by Django 4.2.2 on 2023-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('ka', 'Georgian'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ja', 'Japanese'), ('ru', 'Russian'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('it', 'Italian')], max_length=50),
        ),
    ]
